In [2]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 0, 3, 2, 1])

# Get the unique values from the array
unique_values = np.unique(array_1d)

# Create a one-hot encoded array
one_hot_array = np.eye(6)[array_1d]

# Print the one-hot encoded array
print(one_hot_array)


[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]]


In [1]:
import torch  # type: ignore
from torch import nn
import pickle
import os
import torch
from typing import List

import numpy as np



device = "cuda"
path = "/root/share/dataset/tlp/save_model_v1/tlp_model_14.pkl"
with open(path, 'rb') as f:
    model = pickle.load(f)
model.to(device)
model = model.module
model = torch.nn.DataParallel(model, device_ids=[0, 1, 2, 3, 4, 5, 6, 7])
save_path = "/root/share/dataset/tlp/save_model_v1/tlp_14.pth"
torch.save(model, path)

/root/anaconda3/envs/tvm0/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ImportError: attempted relative import with no known parent package

In [1]:
   import torch

   A = torch.randn(64)
   B = torch.randn(80)

   # Reshape A and B for broadcasting
   A = A.reshape(1, 64)
   B = B.reshape(80, 1)

   # Perform element-wise operation with broadcasting
   result = A + B


/root/anaconda3/envs/tvm0/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
result.shape

torch.Size([80, 64])

In [4]:
A.shape, B.shape

(torch.Size([1, 64]), torch.Size([80, 1]))

In [1]:
my_map = {'a': 1, 'b': 2, 'c': 3}

# Using the values() method to print the values
values = my_map.values()
print(values)


dict_values([1, 2, 3])


In [1]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# Create indices tensor
indices = torch.tensor([[0, 2, 1],
                        [2, 1, 0]])

# Gather values from tensor using indices
gathered_tensor = torch.gather(tensor, dim=1, index=indices)

# Print the gathered tensor
print(gathered_tensor)


tensor([[1, 3, 2],
        [6, 5, 4]])


/root/anaconda3/envs/tvm0/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# Create indices tensor
indices1 = torch.tensor([[0,],
                        [2, ]])

# Gather values from tensor using indices
gathered_tensor1 = torch.gather(tensor, dim=1, index=indices1)

# Print the gathered tensor
print(gathered_tensor1)

tensor([[1],
        [6]])


In [6]:
import torch

# Create a tensor
tensor = torch.tensor([[0, 1, 0],
                       [2, 0, 3],
                       [0, 4, 0]])

# Create a tensor
tensor1 = torch.tensor([[0, 1, 2],
                       [2, 0, 3],
                       [0, 4, 1]])

# Find the nonzero positions
nonzero_positions = torch.nonzero(tensor!=tensor1)

# Print the nonzero positions
print(nonzero_positions)


tensor([[0, 2],
        [2, 2]])


In [5]:
tensor==tensor1

tensor([[ True,  True, False],
        [ True,  True,  True],
        [ True,  True, False]])

In [1]:
import numpy as np

# Original 2d numpy array
array = np.array([[1, 2, 3], [4, 5, 6]])

# Padding the array
padded_array = np.pad(array, [(1,1), (2,2)], 'constant', constant_values=0)

print("Padded 2D array:\n", padded_array)


Padded 2D array:
 [[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]]


In [4]:
# Padding the array
padded_array = np.pad(array, [(0,1), (0,2)], 'constant', constant_values=0)
print(padded_array)

[[1 2 3 0 0]
 [4 5 6 0 0]
 [0 0 0 0 0]]


In [1]:
a = [1, 2]

In [2]:
import numpy as np
import torch
b = np.array(a)
c = torch.from_numpy(b)
c

/root/anaconda3/envs/tvm0/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([1, 2])

In [3]:
torch.all()

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [3]:
import torch
def formatter(file, max_order_len=15, max_cond_len=300):
    decode = file["decode"]

    order = file["order"]
    order = torch.from_numpy(order)

    last_embedding = file['last_embedding']
    last_condition = file['last_condition']
    last_condition = torch.from_numpy(last_condition)

    last_ptr_list = file['last_ptr_list']
    run_secs = file['run_secs']

    padding = torch.zeros(
        max_cond_len - last_condition.shape[0]).to(last_condition.device)
    last_condition = torch.cat([last_condition, padding], 0)

    padding0 = torch.zeros(max_order_len - order.shape[0])
    order = torch.cat([order, padding0], 0)

    return decode, order, last_embedding, run_secs, last_condition, last_ptr_list


/root/anaconda3/envs/tvm0/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
a = torch.zeros(3)
a.shape

torch.Size([3])

In [16]:
n = a.shape[0]
n

3

In [17]:
type(n)

int

In [19]:
b = torch.zeros((3, 4))
b.shape

torch.Size([3, 4])

In [22]:
tt = tuple([b])

In [23]:
tt

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),)

In [24]:
len(tt)

1

In [18]:
n, m = b.shape
n, m

(3, 1)

In [8]:
a == b

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [9]:
a.ndim

1

In [10]:
b.ndim

2

In [4]:
import glob 
import os 
import numpy as np
info_path = "/root/share/dataset/decode_info"
npz_file0 = sorted(glob.glob(os.path.join(
    info_path, f"info0.npz"), recursive=True))
file0 = npz_file0[0]
file0 = np.load(file0)


In [5]:
info0 = formatter(file0)
decode0, order0, x0, run_secs0, cond0, ptr0 = info0
decode0

KeyError: 'last_embedding is not a file in the archive'

In [2]:
a = [12]*10
a

[12, 12, 12, 12, 12, 12, 12, 12, 12, 12]

In [1]:
from joblib import Parallel, delayed

def square(x):
    return x ** 2

numbers = [1, 2, 3, 4, 5]

# Parallelize the for loop using Joblib
result = Parallel(n_jobs=-1)(delayed(square)(num) for num in numbers)

print(result)

ModuleNotFoundError: No module named 'joblib'

In [ ]:
a = [1, 2, 3]


In [17]:
from multiprocessing import Pool, TimeoutError
import time
from multiprocessing import Process, Value, Array
import os

def f(x):
    return x**2


# start 4 worker processes
with Pool(processes=4) as pool:

    # print "[0, 1, 4,..., 81]"
    t = pool.map(f, range(10))

print(t)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [19]:
record_path = "/root/share/dataset/tlp_dataset0"
res = os.path.join(record_path, f"workloads_{0}.json")
print(res)

/root/share/dataset/tlp_dataset0/workloads_0.json


In [14]:
t = []
def g(x):
    t.append(x*x)

# start 4 worker processes
with Pool(processes=4) as pool:
    # print "[0, 1, 4,..., 81]"
    pool.map_async(g, range(10))

print(t)

[]


In [1]:
import torch
import torch.utils.data as Data
torch.manual_seed(1)


/root/anaconda3/envs/tvm0/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
x = torch.linspace(1, 10, 10)
y = torch.linspace(10, 1, 10)
x, y

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,  1.]))

In [4]:
BATCH_SIZE = 2
torch_dataset = Data.TensorDataset(x, y)
loader = Data.DataLoader(
    dataset = torch_dataset,
    batch_size = BATCH_SIZE,
    shuffle = True,
    num_workers = 2
)


In [9]:
loader0 = Data.DataLoader(
    dataset = torch_dataset,
    batch_size = BATCH_SIZE,
    shuffle = False,   
    num_workers = 2
)


In [10]:

for epoch in range(3):
    for step, (batchX, batchY) in enumerate(loader0):
        print('Epoch: ', epoch, '| Step: ', step, '| batch x: ',
              batchX.numpy(), '| batch y: ', batchY.numpy())


Epoch:  0 | Step:  0 | batch x:  [1. 2.] | batch y:  [10.  9.]
Epoch:  0 | Step:  1 | batch x:  [3. 4.] | batch y:  [8. 7.]
Epoch:  0 | Step:  2 | batch x:  [5. 6.] | batch y:  [6. 5.]
Epoch:  0 | Step:  3 | batch x:  [7. 8.] | batch y:  [4. 3.]
Epoch:  0 | Step:  4 | batch x:  [ 9. 10.] | batch y:  [2. 1.]
Epoch:  1 | Step:  0 | batch x:  [1. 2.] | batch y:  [10.  9.]
Epoch:  1 | Step:  1 | batch x:  [3. 4.] | batch y:  [8. 7.]
Epoch:  1 | Step:  2 | batch x:  [5. 6.] | batch y:  [6. 5.]
Epoch:  1 | Step:  3 | batch x:  [7. 8.] | batch y:  [4. 3.]
Epoch:  1 | Step:  4 | batch x:  [ 9. 10.] | batch y:  [2. 1.]
Epoch:  2 | Step:  0 | batch x:  [1. 2.] | batch y:  [10.  9.]
Epoch:  2 | Step:  1 | batch x:  [3. 4.] | batch y:  [8. 7.]
Epoch:  2 | Step:  2 | batch x:  [5. 6.] | batch y:  [6. 5.]
Epoch:  2 | Step:  3 | batch x:  [7. 8.] | batch y:  [4. 3.]
Epoch:  2 | Step:  4 | batch x:  [ 9. 10.] | batch y:  [2. 1.]


In [5]:

for epoch in range(3):
    for step, (batchX, batchY) in enumerate(loader):
        print('Epoch: ', epoch, '| Step: ', step, '| batch x: ',
              batchX.numpy(), '| batch y: ', batchY.numpy())


Epoch:  0 | Step:  0 | batch x:  [5. 3.] | batch y:  [6. 8.]
Epoch:  0 | Step:  1 | batch x:  [1. 7.] | batch y:  [10.  4.]
Epoch:  0 | Step:  2 | batch x:  [9. 8.] | batch y:  [2. 3.]
Epoch:  0 | Step:  3 | batch x:  [10.  2.] | batch y:  [1. 9.]
Epoch:  0 | Step:  4 | batch x:  [6. 4.] | batch y:  [5. 7.]
Epoch:  1 | Step:  0 | batch x:  [5. 9.] | batch y:  [6. 2.]
Epoch:  1 | Step:  1 | batch x:  [2. 6.] | batch y:  [9. 5.]
Epoch:  1 | Step:  2 | batch x:  [1. 3.] | batch y:  [10.  8.]
Epoch:  1 | Step:  3 | batch x:  [4. 7.] | batch y:  [7. 4.]
Epoch:  1 | Step:  4 | batch x:  [10.  8.] | batch y:  [1. 3.]
Epoch:  2 | Step:  0 | batch x:  [6. 9.] | batch y:  [5. 2.]
Epoch:  2 | Step:  1 | batch x:  [4. 8.] | batch y:  [7. 3.]
Epoch:  2 | Step:  2 | batch x:  [ 7. 10.] | batch y:  [4. 1.]
Epoch:  2 | Step:  3 | batch x:  [3. 2.] | batch y:  [8. 9.]
Epoch:  2 | Step:  4 | batch x:  [1. 5.] | batch y:  [10.  6.]


In [7]:
for epoch in range(3):
    batchX, batchY = next(iter(loader))
    print('Epoch: ', epoch, '| batch x: ',
            batchX.numpy(), '| batch y: ', batchY.numpy())


Epoch:  0 | batch x:  [3. 4.] | batch y:  [8. 7.]
Epoch:  1 | batch x:  [ 4. 10.] | batch y:  [7. 1.]
Epoch:  2 | batch x:  [10.  3.] | batch y:  [1. 8.]


In [1]:
import torch

# Define two tensors to concatenate
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Concatenate the tensors along the first dimension
z = torch.cat([x, y], dim=0)

# Split the concatenated tensor back into its original inputs
x_new, y_new = torch.split(z, [3, 3], dim=0)

# Print the original tensors and the split tensors
print("Original tensors:")
print("x =", x)
print("y =", y)
print()
print("Split tensors:")
print("x_new =", x_new)
print("y_new =", y_new)


Original tensors:
x = tensor([1, 2, 3])
y = tensor([4, 5, 6])

Split tensors:
x_new = tensor([1, 2, 3])
y_new = tensor([4, 5, 6])


/root/anaconda3/envs/tvm0/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# Split the concatenated tensor back into its original inputs
x_new, y_new = torch.split(z, [6, 0], dim=0)
# Print the original tensors and the split tensors
print("Original tensors:")
print("x =", x)
print("y =", y)
print()
print("Split tensors:")
print("x_new =", x_new)
print("y_new =", y_new)

Original tensors:
x = tensor([1, 2, 3])
y = tensor([4, 5, 6])

Split tensors:
x_new = tensor([1, 2, 3, 4, 5, 6])
y_new = tensor([], dtype=torch.int64)


In [4]:
import torch
import torch.nn.functional as Fun
A = torch.tensor([3, 4, 5, 0, 1, 2])
output = Fun.one_hot(A, num_classes = 7)
print(output)

tensor([[0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0]])


In [23]:
print(output.view(2, -1))

tensor([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]])


In [24]:
output

tensor([[0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0]])

In [26]:
o1 = list(output.numpy())
o1

[array([0, 0, 0, 1, 0, 0, 0]),
 array([0, 0, 0, 0, 1, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0]),
 array([1, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0])]

In [5]:
# Create a PyTorch tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

In [6]:
for i in tensor:
    print(i)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [18]:
t = [1, 2]

In [19]:
t += (3, 3)

In [20]:
t

[1, 2, 3, 3]

In [21]:
t += [[1, 2, 3,]]

In [22]:
t

[1, 2, 3, 3, [1, 2, 3]]